12

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -29,7 +29,7 @@ jobs:
     - name: verify application.yml replaced
       run: |
         echo "placeholder remaining lines:"
-        grep -n ##auth_key_seoul_data## -n ./config/application.yml || echo "placeholder not found"
+        grep -n ##auth_key_seoul_data## ./config/application.yml && echo "placeholder still in application.yml" || echo "placeholder not found"
 
     - name: archive to tar.gz
       run: tar cvfz ./kafka-producer.tar.gz *
